// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using web.api.demarcacao.gestao.terreno.Data.Context;

namespace web.api.demarcacao.gestao.terreno.Data.Migrations
{
    [DbContext(typeof(DemarcacaoGestaoTerrenoPostgressContext))]
    partial class DemarcacaoGestaoTerrenoPostgressContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("web.api.demarcacao.gestao.terreno.Domain.Entities.Coordenada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("IdTerreno")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_TERRENO");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("LONGITUDE");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ORDEM");

                    b.HasKey("Id");

                    b.HasIndex("IdTerreno");

                    b.ToTable("COORDENADA");
                });

            modelBuilder.Entity("web.api.demarcacao.gestao.terreno.Domain.Entities.Terreno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("IdEmpreendimento")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_EMPREENDIMENTO");

                    b.HasKey("Id");

                    b.ToTable("TERRENO");
                });

            modelBuilder.Entity("web.api.demarcacao.gestao.terreno.Domain.Entities.Coordenada", b =>
                {
                    b.HasOne("web.api.demarcacao.gestao.terreno.Domain.Entities.Terreno", "Terreno")
                        .WithMany("Coordenadas")
                        .HasForeignKey("IdTerreno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terreno");
                });

            modelBuilder.Entity("web.api.demarcacao.gestao.terreno.Domain.Entities.Terreno", b =>
                {
                    b.Navigation("Coordenadas");
                });
#pragma warning restore 612, 618
        }
    }
}
