version: "3.9"
services:
  demarcacao-gestao-terreno-web:
    build:
      context: ../..
      dockerfile: web.api.demarcacao.gestao.terreno.Endpoint/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - local_env.yaml
    container_name: demarcacao.gestao.terreno.web
